name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test&#45;t01&#45;01
      id: test-45-t01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test&#45;t01&#45;01
        setup-command: make compile
        command: make -s test
        input: |-
          978-0201498400
          Data Structures and Algorithm Analysis in C
          Mark Allen Weiss
          1996
          Pearson
          yes
          84.21
          20.12
          0
          4.6
        expected-output: 978-0201498400|Data Structures and Algorithm Analysis in
          C|Mark Allen Weiss|1996|Pearson|yes|84.21|20.12|0|4.6
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: test&#45;t01&#45;02
      id: test-45-t01-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test&#45;t01&#45;02
        setup-command: make compile
        command: make -s test
        input: |-
          978-0130895929
          C: A Reference Manual
          Samuel Harbison, Guy Steele Jr.
          2002
          Pearson
          no
          50.19
          11.05
          21
          4.1
        expected-output: '978-0130895929|C: A Reference Manual|Samuel Harbison, Guy
          Steele Jr.|2002|Pearson|no|50.19|11.05|21|4.1'
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: test&#45;t01&#45;03
      id: test-45-t01-45-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test&#45;t01&#45;03
        setup-command: make compile
        command: make -s test
        input: |-
          978-0439708180
          Harry Potter and the Sorcerer's Stone
          J.K. Rowling
          1998
          Scholastic
          no
          14.15
          9.55
          16
          4.8
        expected-output: 978-0439708180|Harry Potter and the Sorcerer's Stone|J.K.
          Rowling|1998|Scholastic|no|14.15|9.55|16|4.8
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: test&#45;t01&#45;04
      id: test-45-t01-45-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test&#45;t01&#45;04
        setup-command: make compile
        command: make -s test
        input: |-
          978-9332573901
          Computer Systems: A Programmer's Perspective
          David R. O'Hallaron, Randal E. Bryant
          2016
          Pearson
          yes
          80.45
          10.05
          0
          4.3
        expected-output: '978-9332573901|Computer Systems: A Programmer''s Perspective|David
          R. O''Hallaron, Randal E. Bryant|2016|Pearson|yes|80.45|10.05|0|4.3'
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: test&#45;t01&#45;05
      id: test-45-t01-45-05
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test&#45;t01&#45;05
        setup-command: make compile
        command: make -s test
        input: |-
          978-1780173641
          Computational Thinking: A beginner's guide to problem-solving and programming
          Karl Beecher
          2017
          BCS
          yes
          27.49
          2.14
          0
          4.4
        expected-output: '978-1780173641|Computational Thinking: A beginner''s guide
          to problem-solving and programming|Karl Beecher|2017|BCS|yes|27.49|2.14|0|4.4'
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-45-T01-45-01_RESULTS: "${{steps.test-45-t01-45-01.outputs.result}}"
        TEST-45-T01-45-02_RESULTS: "${{steps.test-45-t01-45-02.outputs.result}}"
        TEST-45-T01-45-03_RESULTS: "${{steps.test-45-t01-45-03.outputs.result}}"
        TEST-45-T01-45-04_RESULTS: "${{steps.test-45-t01-45-04.outputs.result}}"
        TEST-45-T01-45-05_RESULTS: "${{steps.test-45-t01-45-05.outputs.result}}"
      with:
        runners: test-45-t01-45-01,test-45-t01-45-02,test-45-t01-45-03,test-45-t01-45-04,test-45-t01-45-05
